hngi/lancers

resources/views/Create_password.blade.php, resources/views/layouts/master.blade.php, resources/views/passwordreset.blade.php, resources/views/passwordresetconfirmation.blade.php, resources/views/passwordresetmessage.blade.php, routes/web.php
=> created some new views

app/Http/Controllers/ProjectController.php
Project not returning json anymore is verified.
=> Final verification of task done

app/Http/Controllers/Auth/RegisterController.php, resources/views/auth/register.blade.php
=> register fix

app/Http/Controllers/Auth/RegisterController.php
=> second fix register

app/Http/Controllers/GuestController.php, resources/views/guests/contact_support.blade.php, resources/views/pricing.blade.php, routes/web.php
Added the frontend
added route
pushing now for my partner to work on
=>  Contact support

resources/views/auth/login.blade.php, resources/views/auth/register.blade.php, resources/views/layouts/auth.blade.php, resources/views/layouts/authinvoice.blade.php, resources/views/pricing.blade.php
The patch makes routes every lancer logo on the pricing, login and sign-up views to the welcome view.
That's a bug fix requested by `@Alphajeez-Pm` (on slack)
=> Route lancer logo to welcome view

app/Http/Controllers/GuestController.php, resources/views/guests/contact_support.blade.php, routes/web.php
Added the frontend
added route
pushing now for my partner to work on
=> Finished up Contact Support

app/Http/Controllers/GuestController.php, resources/views/guests/contact_support.blade.php, routes/web.php
=> Revert "Finished up Contact Support"

resources/views/eval_estimation.blade.php, routes/web.php
Created 'eval_estimation.blade.php' file and added its route url 'web.php'
=> Blade file and route URL for 'evaluate estimation' created

app/Http/Controllers/emailsettingsController.php
Fixed bug with email settings controller
=> Fixed bug with email settings controller

database/seeds/bugfix.php
countries,states,subscription,curencies bugfix seeder
=> countries,states,subscription,curencies bugfix seeder

resources/views/layouts/auth.blade.php
resources/layouts/auth.blade.php
=> dashboard fix

app/Http/Controllers/ProfileController.php, resources/views/settings_profile.blade.php, routes/web.php
Fixed errors with profile form submission
=> Fixed errors with profile form submission

app/Estimate.php, app/Http/Controllers/EstimateController.php, app/Http/Controllers/InvoiceController.php, app/Invoice.php, app/Project.php, database/migrations/2019_10_09_214601_create_projects_table.php, database/migrations/2019_10_09_214740_create_estimates_table.php, database/migrations/2019_10_09_215235_create_invoices_table.php, resources/views/invoices/invoicelist.blade.php, resources/views/invoices/list.blade.php, resources/views/invoices/reviewinvoice.blade.php, routes/web.php
Lancer invoice procced to review bug fix and invoice list view done
note that a foreign key was build and i remove uneccessary IDS and model that dont have to be inside each one another .
A migrate fresh is needed when merge
=> Invoice view list and bug fix in review and build foreign keys

resources/views/contracts.blade.php
Kindly review file for testing and recommend any bugs for correction.
=> Contracts Blade File Moved to Users Folder

resources/views/pricing.blade.php
Effected the changes to the blade: the navbar, the number formats, 'B…ack to up' changed to Arrow button, The logo on the footer has been fixed...
=> Effected changes made by @Lakech FrontDev 

resources/views/welcome.blade.php
these bugs include footer not properly done, wrong office address on the footer page and some links not functioning.
=> fixed bugs on welcome.blade.php

app/Client.php, app/Http/Controllers/EstimateController.php, app/Http/Controllers/InvoiceController.php, app/Invoice.php, database/migrations/2019_10_09_215235_create_invoices_table.php, database/seeds/DatabaseSeeder.php, resources/views/invoices/clientinvoice.blade.php
invoice send mail done but check your env for maill setting
=> invoice send mail done but check your env for maill setting

app/Http/Controllers/ProjectController.php, app/Http/Controllers/TaskController.php, app/Providers/RouteServiceProvider.php, database/seeds/DatabaseSeeder.php, database/seeds/TasksTableSeeder.php, routes/api.php
review and test for authenticated users to add, edit, delete and list collaborators and tasks
=> tasks and collaborators bugs fixed

app/Http/Controllers/MailSubscriptionController.php, app/MailSubscription.php, database/migrations/2019_10_24_152217_create_mail_subscriptions_table.php, resources/views/pricing.blade.php, resources/views/welcome.blade.php, routes/web.php
-With this feature, users and guests can subscribe to the app's mailing list
-Created controller and mode for this feature created
-Migration file created
-Correct links inserted in blade files that have the Front end of this feature
=> Implemented 'mailing list subscription' feature

app/Http/Controllers/GuestController.php
fix minor bug on guest estimate on contact
=> fix minor bug on guest estimate on contact

app/Http/Controllers/InvoiceController.php, resources/views/invoices/list.blade.php
fix error on handling Email Error for now
=> fix error on handling Email Error for now 

app/Http/Controllers/ClientController.php
fix client project showing other work no error
=> fix client project showing other work no error

app/Http/Controllers/ClientController.php, resources/views/clients/list.blade.php, resources/views/estimate/step1.blade.php, resources/views/invoices/list.blade.php, routes/web.php
=> Revert "Update the Plus and return button functionality on Invoice and fix bug on filter"

resources/views/estimate/step3.blade.php, resources/views/estimate/step4.blade.php
Current page: https://dev.lancers.app/estimate/create/step4
PR on the frontend repo: https://github.com/hngi/newLancerApp/pull/64
hosted page: https://teamtreasurehng.000webhostapp.com/create_estimate_step4.html
localhost screenshot:
Current page: https://dev.lancers.app/estimate/create/step3
PR on the frontend repo: https://github.com/hngi/newLancerApp/pull/66
hosted page: http://nkechi10.github.io/estimate-page.html
localhost screenshot:
=> Blade implementation for bug fix on creating estimate step4 & step3 view

app/Http/Controllers/ProjectController.php, resources/views/layouts/auth.blade.php, resources/views/trackproject.blade.php
-Deleted duplicate models in ProjectController.php
-Changed profile image for user with no image auth.blade.php
-Fixed responsiveness of trackproject.blade.php
=> Fixed 'ProjectController.php', 'auth.blade.php', 'trackproject.blade.php'

app/Http/Controllers/EstimateController.php, resources/views/estimate/step3.blade.php, resources/views/estimate/step4.blade.php
Fix the step 5 error and update the controllers
=> Backup for step five 

app/Http/Controllers/ClientController.php, resources/views/client-info.blade.php, resources/views/clients/list.blade.php, resources/views/layouts/auth.blade.php, routes/web.php
This feature enables users to view client information from the clients list page
=> View client functionality

resources/views/invoices/list.blade.php
invoice blade files updated for Creating and deleting invoice
=> @blinshine

resources/views/estimate/step2.blade.php, resources/views/estimate/step4.blade.php, resources/views/guests/step2.blade.php, resources/views/guests/step4.blade.php, resources/views/projects/edit.blade.php
@blinshine worked on validation done of all form number inputs
=> validation done on all form number inputs

mail.php, resources/views/clients/edit.blade.php, resources/views/projects/invite.blade.php, resources/views/projects/list.blade.php, routes/web.php
all tasks related to bugs from client crud, invite, task and project list (WIP) fixed
=> Dev from @blinshine

resources/views/invoices/clientinvoice.blade.php, resources/views/invoices/invoicesent.blade.php, resources/views/invoices/reviewinvoice.blade.php, resources/views/payment.blade.php, resources/views/paystackpay.blade.php
=> Revert "fix invoice sent message and invoice payment, and etimate based on cu…"

app/Http/Controllers/PaymentContoller.php, app/Http/Controllers/RaveController.php, app/Http/Middleware/VerifyCsrfToken.php, app/Invoice.php, composer.json, composer.lock, config/app.php, config/rave.php, resources/views/invoices/clientinvoice.blade.php, resources/views/invoices/invoicesent.blade.php, resources/views/paystackpay.blade.php, routes/web.php
invoice pay with flutterwave , rember to run composer update or install
=> invoice pay with flutterwave , rember to run composer update or install

app/Http/Controllers/InvoiceController.php
=> fix trackcode

resources/views/invoices/clientinvoice.blade.php
invoice client page with print and download pdf done
=> invoice client page with print and download pdf done

resources/views/trackproject.blade.php, routes/web.php
Nav bar and footer include in track blade
=> Dev from @blinshine 

app/Http/Controllers/InvoiceController.php, app/Http/Controllers/ProjectController.php, database/migrations/2019_10_09_214742_create_invoices_table.php, resources/views/client-doc-view.blade.php, resources/views/invoices/reviewinvoice.blade.php, resources/views/pdf/trackproject.blade.php
Implementation details:
-User can select colour of invoice
-Invoice migration file, project and invoice controllers, blade files, all modified to store and access
invoice colour
=> Invoice color change feature

app/Http/Controllers/InvoiceController.php, app/Http/Controllers/SubscriptionController.php, resources/views/clients/list.blade.php, resources/views/invoices/list.blade.php, resources/views/layouts/app.blade.php, resources/views/projects/collaborators.blade.php, resources/views/projects/tasks.blade.php, routes/web.php
Wrote JS and PHP code to ensure delete functions for invoice,clients,task,collaborators set confirmation messages via modals and worked properly
=> Wrote JS and PHP code to ensure delete functions for invoice,clients,task,collaborators set confirmation messages via modals and worked properly

app/Http/Controllers/PaymentContoller.php, app/Http/Controllers/RaveController.php, app/Http/Controllers/SubscriptionController.php, resources/views/paystackpay.blade.php, resources/views/pricing.blade.php
subscription plan done with flutterwave
=> subscription plan done with flutterwave

resources/views/pricing.blade.php
=> rename plan name

resources/views/create_invoice.blade.php, resources/views/manage_project.blade.php, resources/views/track_project_description.blade.php, resources/views/welcome.blade.php, routes/web.php
all bugs fixed, files updated and new files created
=> Dev from @oluwablin
